config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'courses/reload', to: 'courses#reload'
  devise_for :users
  resources :users
  resources :availabilities
  resources :applications
  resources :recommendations
  resources :sections
  resources :courses
  resources :enrollments
  resources :admin
  authenticate :user do
    root to: 'courses#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name role is_approved])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
  include Pagy::Backend
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: %i[show edit update destroy]

  # GET /applications or /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1 or /applications/1.json
  def show; end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit; end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)
    @application.approved = false if @application.approved.nil?
    respond_to do |format|
      if @application.save
        format.html { redirect_to(application_url(@application), notice: "Application was successfully created.") }
        format.json { render(:show, status: :created, location: @application) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @application.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        if params[:approved] == "true"
          @application.course.increment!(:graders)
        end
        format.html { redirect_to(application_url(@application), notice: "Application was successfully updated.") }
        format.json { render(:show, status: :ok, location: @application) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @application.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy

    respond_to do |format|
      format.html { redirect_to(applications_url, notice: "Application was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = Application.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def application_params
    if params[:application]
      params.require(:application).permit(:user_id, :course_id, :approved)
    else
      params.permit(:approved)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  TERM_OPTIONS = {
    '1232' => 'Spring 2023',
    '1234' => 'Summer 2023',
    '1238' => 'Autumn 2023'
    # Add more term mappings as needed
  }.freeze

  def term_options_for_select
    TERM_OPTIONS.map { |number, name| [name, number] }
  end

  def sort_order
    %w[asc desc].include?(params[:sort]) ? params[:sort] : 'asc'
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_application.html.erb
<div id="<%= dom_id application %>" class="card bg-light mb-3">
  <div class="card-header font-weight-bold">Application Information</div>
  <div class="card-body">

    <p class="mb-1">
      <strong>Email:</strong>
      <span class="ml-2"><%= application.user.email %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>Role:</strong>
      <span class="ml-2"><%= application.user.role %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>First:</strong>
      <span class="ml-2"><%= application.user.first_name %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>Last:</strong>
      <span class="ml-2"><%= application.user.last_name %></span>
    </p>
    <hr class="dashed"/>
    <p class="mb-1">
      <strong>Course Number:</strong>
      <span class="ml-2"><%= application.course.course_number %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>Term:</strong>
      <span class="ml-2"><%= application.course.term %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>Subject:</strong>
      <span class="ml-2"><%= application.course.subject %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>Course:</strong>
      <span class="ml-2"><%= application.course.name %></span>
    </p>
    <hr/>
    <p class="mb-1">
      <strong>Description:</strong>
      <span class="ml-2"><%= application.course.description %></span>
    </p>
  </div>
</div>

app/views/applications/_form.html.erb
<%= form_with(model: application, local: true, html: { class: 'form-horizontal', role: 'form' }) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
    <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>
    <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <% if current_user.role == "Admin" %>
    <div class="form-group">
      <%= form.label :user_id, class: 'control-label' %>
      <%= form.collection_select :user_id, User.order(:first_name), :id, :full_name, {}, { class: 'form-control' } %>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :user, class: 'control-label' %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <label for="staticUser"></label><input type="text" readonly class="form-control" id="staticUser" value="<%= "#{current_user.full_name}" %>">
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :course_id, class: 'control-label' %>
    <%= form.collection_select :course_id, Course.order(:course_number), :id, :full_course, {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<div class="container my-4">
  <div class="card-body">

    <h2 class="card-title text-center">Editing Application</h2>

    <%= render "form", application: @application %>

    <div class="mt-3 text-center">
      <%= link_to "Show this application", @application, class: "btn btn-primary" %>
      <%= link_to "Back to applications", applications_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/applications/index.html.erb
<div class="container mt-5">
  <% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h2 class="mb-4">My Applications</h2>

  <table id="coursesTable" class="table table-striped table-bordered mt-3">
    <thead class="thead-light">
    <tr id="headerRow">
      <th class="text-center">Course Number</th>
      <th class="text-center">Term</th>
      <th class="text-center">Name</th>
      <th class="text-center">Subject</th>
      <th class="text-center">User</th>
      <th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @applications.where(user_id: current_user.id).each do |application| %>
      <tr>
        <td class="text-center"><%= application.course.course_number %></td>
        <td class="text-center"><%= application.course.term %></td>
        <td class="text-center"><%= application.course.name %></td>
        <td class="text-center"><%= application.course.subject %></td>
        <td class="text-center"><%= application.user.email %></td>
        <td class="text-center">
          <%= link_to "Show this Application", application, class: "btn btn-info" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to "New application", new_application_path, class: "btn btn-success" %>
</div>

app/views/applications/new.html.erb
<div class="container my-4">
  <div class="card-body">

    <h2 class="card-title text-center">New Application</h2>

    <%= render "form", application: @application %>

    <div class="row mt-4">
      <%= link_to "Back to applications", applications_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/applications/show.html.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>

<div class="container">
  <%= render @application %>

  <div>
    <h2>Course History</h2>
    <table id="coursesTable" class="table table-striped mt-3">
      <thead class="thead-light">
      <tr>
        <th class="text-center">Course</th>
        <th class="text-center">Grade</th>
      </tr>
      </thead>

      <tbody>
      <% @application.user.enrollments.each do |enrollment| %>
        <tr>
          <td class="text-center"><%= enrollment.course_name %></td>
          <td class="text-center"><%= enrollment.grade %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <h2>Availabilities</h2>
    <table id="coursesTable" class="table table-striped mt-3">
      <thead class="thead-light">
      <tr>
        <th class="text-center">Day</th>
        <th class="text-center">Start Time</th>
        <th class="text-center">End Time</th>
      </tr>
      </thead>

      <tbody>
      <% @application.user.availabilities.each do |availability| %>
        <tr>
          <td class="text-center"><%= availability.day %></td>
          <td class="text-center"><%= availability.start_time.strftime("%I:%M %p") %></td>
          <td class="text-center"><%= availability.end_time.strftime("%I:%M %p") %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= link_to "Edit this application", edit_application_path(@application), class: "btn btn-primary" %>
    <%= link_to "Back to applications", applications_path, class: "btn btn-secondary" %>

    <%= button_to "Destroy this application", @application, method: :delete, class: "btn btn-danger" %>

    <% if current_user.role == "Admin" || current_user.role == "Instructor" %>
      <%= form_with(url: application_path(@application), method: :patch) do %>
        <%= hidden_field_tag :approved, true %>
        <%= submit_tag "Approve", class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>