config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'courses/reload', to: 'courses#reload'
  devise_for :users
  resources :users
  resources :availabilities
  resources :applications
  resources :recommendations
  resources :sections
  resources :courses
  resources :enrollments
  resources :admin
  authenticate :user do
    root to: 'courses#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]

  # GET /enrollments
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  def show; end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit; end

  # POST /enrollments
  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.user_id = current_user.id
    course = Course.find(params[:enrollment][:course_id])
    @enrollment.course_name = course.full_course

    if @enrollment.save
      redirect_to(@enrollment, notice: 'Enrollment was successfully created.')
    else
      render(:new)
    end
  end

  # PATCH/PUT /enrollments/1
  def update
    @enrollment.user_id = current_user.id
    course = Course.find(params[:enrollment][:course_id])
    @enrollment.course_name = course.full_course
    if @enrollment.update(enrollment_params)
      redirect_to(@enrollment, notice: 'Enrollment was successfully updated.')
    else
      render(:edit)
    end
  end

  # DELETE /enrollments/1
  def destroy
    @enrollment.destroy
    redirect_to(enrollments_url, notice: 'Enrollment was successfully destroyed.')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def enrollment_params
    params.require(:enrollment).permit(:user_id, :course_name, :grade)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>Course:</strong>
    <%= enrollment.course_name %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= enrollment.grade %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: @enrollment, local: true, class: 'needs-validation', novalidate: '') do |form| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% @enrollment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.label :course_id, class: 'control-label' %>
    <%= form.collection_select :course_id, Course.order(:course_number), :id, :full_course, {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= form.label :grade %>
    <%= form.text_field :grade, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', enrollments_path, class: 'btn btn-secondary' %>

app/views/enrollments/edit.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-header">
      <h2>Editing Enrollment</h2>
    </div>
    <div class="card-body">
      <%= render "form", enrollment: @enrollment %>

      <div class="mt-3">
        <%= link_to "Show this enrollment", @enrollment, class: 'btn btn-info' %>
        <%= link_to "Back to enrollments", enrollments_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/index.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2>My Course History</h2>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table id="enrollmentsTable" class="table table-striped table-hover">
          <thead>
          <tr id="headerRow">
            <th class="text-center">Course</th>
            <th class="text-center">Grade</th>
            <th class="text-center">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @enrollments.where(user_id: current_user.id).each do |enrollment| %>
            <tr>
              <td class="text-center"><%= enrollment.course_name %></td>
              <td class="text-center"><%= enrollment.grade %></td>
              <td class="text-center"><%= link_to 'Show', enrollment, class: 'btn btn-info' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to 'New Enrollment', new_enrollment_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/enrollments/new.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-header">
      <h2>New Enrollment</h2>
    </div>
    <div class="card-body">
      <p class="card-text">This information is self reported, if misconduct is suspected all possibilities of employment
        are void</p>

      <%= form_with(model: @enrollment, local: true, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
        <% if @enrollment.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading"><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment
              from being saved:</h4>
            <ul>
              <% @enrollment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= hidden_field_tag :user_id, current_user.id %>

        <div class="form-group">
          <%= form.label :course_id, class: 'control-label' %>
          <%= form.collection_select :course_id, Course.order(:course_number), :id, :full_course, {}, { class: 'form-control' } %>
        </div>

        <div class="form-group">
          <%= form.label :grade, class: 'form-control-label' %>
          <%= form.text_field :grade, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.submit class: 'btn btn-primary' %>
        </div>
      <% end %>

      <%= link_to 'Back', enrollments_path, class: 'btn btn-secondary mt-4' %>
    </div>
  </div>
</div>

app/views/enrollments/show.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-header">
      <h2>Enrollment Details</h2>
    </div>

    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <div class="card-body">
      <%= render @enrollment %>

      <div class="mt-3 d-flex justify-content-between align-items-center">
        <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment), class: 'btn btn-warning' %>
        <%= link_to "Back to enrollments", enrollments_path, class: 'btn btn-secondary' %>
        <%= button_to "Destroy this enrollment", @enrollment, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>