config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'courses/reload', to: 'courses#reload'
  devise_for :users
  resources :users
  resources :availabilities
  resources :applications
  resources :recommendations
  resources :sections
  resources :courses
  resources :enrollments
  resources :admin
  authenticate :user do
    root to: 'courses#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :require_admin, only: %i[ edit update destroy ]

  # GET /courses or /courses.json
  def index
    @terms = Course.distinct.pluck(:term)

    sort = params[:sort] || 'course_number'
    direction = params[:direction] || 'asc'

    @courses = Course.order(sort => direction)

    if params[:term].present?
      @courses = @courses.where(term: params[:term])
    end

    if params[:search].present?
      @pagy, @courses = pagy(
        @courses.where("course_number LIKE :search OR subject LIKE :search OR name LIKE :search OR description LIKE :search OR level LIKE :search",
                       search: "%#{params[:search]}%")
      )
    else
      @pagy, @courses = pagy(@courses)
    end
  end

  # GET /courses/1 or /courses/1.json
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to(course_url(@course), notice: "Course was successfully created.") }
        format.json { render(:show, status: :created, location: @course) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to(course_url(@course), notice: "Course was successfully updated.") }
        format.json { render(:show, status: :ok, location: @course) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url, notice: "Course was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  # Reload courses.
  def reload
    system("rake db:populate")
    redirect_to(courses_path, notice: 'Courses reloaded.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:course_number, :subject, :name, :description, :short_description, :level, :graders, :graders_required)
  end

  # Only allow admin to take specific action
  def require_admin
    unless current_user.role == 'Admin' && current_user.is_approved == true
      flash[:alert] = "You must be an admin to access this action."
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Course number:</strong>
    <%= course.course_number %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= course.subject %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= course.description %>
  </p>

  <p>
    <strong>Level:</strong>
    <%= course.level %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course, html: { class: 'needs-validation', novalidate: true }) do |form| %>

  <% if course.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(course.errors.count, "error") %> prohibited this course from being
        saved</h4>
      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :course_number %>
    <%= form.text_field :course_number, class: "form-control", placeholder: "Course number" %>
  </div>

  <div class="form-group">
    <%= form.label :subject %>
    <%= form.text_field :subject, class: "form-control", placeholder: "Subject" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= form.label :short_description %>
    <%= form.text_area :short_description, class: "form-control", rows: 3, placeholder: "Short description" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", rows: 3, placeholder: "Description" %>
  </div>

  <div class="form-group">
    <%= form.label :level %>
    <%= form.text_field :level, class: "form-control", placeholder: "Level" %>
  </div>

  <div class="form-group">
    <%= form.label :graders, 'Graders' %>
    <%= form.number_field :graders, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :graders_required, 'Graders Required' %>
    <%= form.number_field :graders_required, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/courses/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1 class="mt-3">Editing Course</h1>
      <%= render "form", course: @course %>

      <div class="mt-3">
        <%= link_to "Show this course", @course, class: "btn btn-primary" %>
        <%= link_to "Back to courses", courses_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<head>
  <title>Course Catalog</title>
  <style>
      #searchBar {
          display: flex;
          align-items: center;
          margin-bottom: 5px; /* Adjust this value as needed */
      }

      #searchInput {
          margin-right: 10px;
      }

      #search-button {
          margin-left: 10px;
      }
  </style>
</head>
<body>

<p style="color: green"><%= notice %></p>

<h1 class="text-center">Course Catalog</h1>

<div>
  <%= form_with url: courses_path, method: :get, local: true, class: "form-inline my-2 my-lg-0", id: "searchBar" do %>
    <%= text_field_tag :search, params[:search], id: "searchInput", placeholder: "Search your Course...", class: "form-control mr-sm-2" %>
    <%= select_tag :term, options_for_select([['All Terms', '']] + term_options_for_select, params[:term]), prompt: 'Select Term', class: "form-control mr-sm-2" %>
    <%= button_tag type: 'submit', name: nil, id: "search-button", class: "btn btn-outline-success my-2 my-sm-0" do %>
      Search
    <% end %>
    <% if current_user&.role == 'Admin' %>
      <div class="ml-auto mr-3">
        <%= link_to "New course", new_course_path, class: "btn btn-success ml-2" %>
        <%= link_to 'Reload Courses', 'courses/reload', method: :get, class: "btn btn-primary ml-2" %>
      </div>
    <% end %>
  <% end %>


  <table id="coursesTable" class="table mt-3">
    <thead>
    <tr id="headerRow">
      <th class="text-center">
        <%= link_to "Course Number", { sort: 'course_number', direction: params[:direction] == 'asc' ? 'desc' : 'asc' }, { class: 'text-primary' } %>
      </th>
      <th class="text-center">Term</th>
      <th class="text-center">Subject</th>
      <th class="text-center">Name</th>
      <th class="text-center">Description</th>
      <th class="text-center">Level</th>
      <th class="text-center">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td class="text-center"><%= course.course_number %></td>
        <td class="text-center"><%= course.term %></td>
        <td class="text-center"><%= course.subject %></td>
        <td class="text-center"><%= course.name %></td>
        <td class="text-center"><%= course.short_description %></td>
        <td class="text-center"><%= course.level %></td>
        <td class="text-center">
          <div class="container">
            <div class="row">
              <div class="column">
                <div class="col">
                  <%= link_to "Show this course", course, class: "btn btn-primary btn-block" %>
                </div>
                <div class="col" style="margin-top: 5px;">
                  <%= form_tag applications_path, method: :post do %>
                    <%= hidden_field_tag :user_id, current_user.id %>
                    <%= hidden_field_tag :course_id, course.id %>
                    <%= hidden_field_tag :approved, false %>
                    <%= button_tag "Apply", class: "btn btn-secondary btn-block", type: "submit" %>
                  <% end %>
                </div>
                <div class="col" style="margin-top: 5px;">
                  <% if current_user&.role == 'Student' %>
                    <%= button_to 'Add to taken Courses', enrollments_path(course_id: course.id), method: :post, class: "btn btn-primary btn-block" %>
                  <% end %>
                </div>
                <div class="col" style="margin-top: 5px;">

                  <% if current_user&.role == 'Admin' && current_user.is_approved == true %>
                    <%= link_to "Delete", course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block" %>
                    <%= link_to "Edit", edit_course_path(course), class: "btn btn-info btn-block" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
</body>

<div class="d-flex justify-content-between align-items-center mt-3 px-4">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/courses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>New Course</h1>

      <%= render "form", course: @course %>

      <br>

      <div>
        <%= link_to "Back to courses", courses_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center"><%= @course.subject %> <%= @course.course_number %> - <%= @course.name %></h1>

<div class="card mb-3">
  <div class="card-body">
    <p class="card-text">Course Name: <%= @course.subject %> <%= @course.course_number %> - <%= @course.name %></p>
    <p class="card-text">
    <p class="text-muted">Description: <%= @course.description %></p>
  </div>
</div>

<div class="mt-3">
  <table class="table">
    <thead>
    <tr>
      <th>Section Number</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Days of Week</th>
      <th>Instruction Mode</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @course.sections.each do |section| %>
      <tr>
        <td><%= section.section_number %></td>
        <td><%= section.start_time.strftime("%I:%M %p") %>
        <td><%= section.end_time.strftime("%I:%M %p") %></td>
        <td><%= section.days %></td>
        <td><%= section.instruction_mode %></td>
        <td class="text-center">
          <div class="container">
            <div class="row">
              <div class="column">
                <div class="col">
                  <% if current_user.role == "Admin" %>
                    <%= link_to "Edit this Section", edit_section_path(section), class: "btn btn-primary btn-block" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="d-flex justify-content-start px-4 mt-3">
  <%= link_to "Edit this course", edit_course_path(@course), class: 'btn btn-primary mr-2' %>
  <%= link_to "Back to courses", courses_path, class: 'btn btn-secondary mr-2' %>
  <%= button_to "Delete this course", @course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>