config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'courses/reload', to: 'courses#reload'
  devise_for :users
  resources :users
  resources :availabilities
  resources :applications
  resources :recommendations
  resources :sections
  resources :courses
  resources :enrollments
  resources :admin
  authenticate :user do
    root to: 'courses#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
  validates :start_time, presence: true
  validates :end_time, presence: true
  enum day: { Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 }
end

app/models/course.rb
class Course < ApplicationRecord
  validates(:course_number, :subject, :name, presence: true)
  validates :course_number, uniqueness: { scope: :term, message: "and term combination should be unique" }
  has_many :applications, dependent: :destroy
  has_many :sections, dependent: :destroy

  def self.sorted_by_course_number(sort_order)
    if sort_order == 'desc'
      order("CAST(course_number AS INTEGER) DESC")
    else
      order("CAST(course_number AS INTEGER) ASC")
    end
  end

  def full_course
    "#{course_number} - #{name}"
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :enrollments
  belongs_to :course
  validates :section_number, uniqueness: { scope: :term, message: "and term combination should be unique" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :enrollments, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  validates(:email, format: { with: /\b[A-Z0-9._%a-z\-]+@osu\.edu\z/, message: "must be a @osu.edu account" })
  validates(:first_name, :last_name, :role, presence: true)

  def full_name
    "#{first_name}  #{last_name} (#{email})"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
    # Your admin dashboard logic here
  end

  def users
    # Logic to display a list of users in the admin panel
    @users = User.all
  end

  def index
    @applications = Application.all
    @sections = Section.all
    @users = User.all
    @courses = Course.all
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :require_admin, only: %i[ edit update destroy ]

  # GET /courses or /courses.json
  def index
    @terms = Course.distinct.pluck(:term)

    sort = params[:sort] || 'course_number'
    direction = params[:direction] || 'asc'

    @courses = Course.order(sort => direction)

    if params[:term].present?
      @courses = @courses.where(term: params[:term])
    end

    if params[:search].present?
      @pagy, @courses = pagy(
        @courses.where("course_number LIKE :search OR subject LIKE :search OR name LIKE :search OR description LIKE :search OR level LIKE :search",
                       search: "%#{params[:search]}%")
      )
    else
      @pagy, @courses = pagy(@courses)
    end
  end

  # GET /courses/1 or /courses/1.json
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to(course_url(@course), notice: "Course was successfully created.") }
        format.json { render(:show, status: :created, location: @course) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to(course_url(@course), notice: "Course was successfully updated.") }
        format.json { render(:show, status: :ok, location: @course) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url, notice: "Course was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  # Reload courses.
  def reload
    system("rake db:populate")
    redirect_to(courses_path, notice: 'Courses reloaded.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:course_number, :subject, :name, :description, :short_description, :level, :graders, :graders_required)
  end

  # Only allow admin to take specific action
  def require_admin
    unless current_user.role == 'Admin' && current_user.is_approved == true
      flash[:alert] = "You must be an admin to access this action."
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(user_url(@user), notice: "User was successfully created.") }
        format.json { render(:show, status: :created, location: @user) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to(user_url(@user), notice: "User was successfully updated.") }
        format.json { render(:show, status: :ok, location: @user) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url, notice: "User was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :role, :is_approved)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  TERM_OPTIONS = {
    '1232' => 'Spring 2023',
    '1234' => 'Summer 2023',
    '1238' => 'Autumn 2023'
    # Add more term mappings as needed
  }.freeze

  def term_options_for_select
    TERM_OPTIONS.map { |number, name| [name, number] }
  end

  def sort_order
    %w[asc desc].include?(params[:sort]) ? params[:sort] : 'asc'
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/course_takens_helper.rb
module CourseTakensHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin Portal</h1>
<hr/>

<% if current_user.role == 'Admin' && current_user.is_approved == true %>
  <h2>Courses Needing Graders</h2>
  <table id="gradersTable" class="table mt-3">
    <thead>
    <tr id="graderHeaderRow">
      <th class="text-center">Name</th>
      <th class="text-center">Course Number</th>
      <th class="text-center">Term</th>
      <th class="text-center">Current Graders</th>
      <th class="text-center">Graders Required</th>
    </tr>
    </thead>
    <tbody>
    <% @courses.where('graders < graders_required').each do |course| %>
      <tr>
        <td class="text-center"><%= course.name %></td>
        <td class="text-center"><%= course.course_number %></td>
        <td class="text-center"><%= course.term %></td>
        <td class="text-center"><%= course.graders %></td>
        <td class="text-center"><%= course.graders_required %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br/>

  <h2>Users</h2>
  <table id="coursesTable" class="table mt-3">
    <thead>
    <tr id="headerRow">
      <th class="text-center">Email</th>
      <th class="text-center">First</th>
      <th class="text-center">Last</th>
      <th class="text-center">Role</th>
      <th class="text-center">Approved</th>
      <th class="text-center">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="text-center"><%= user.email %></td>
        <td class="text-center"><%= user.first_name %></td>
        <td class="text-center"><%= user.last_name %></td>
        <td class="text-center"><%= user.role %></td>
        <td class="text-center"><%= user.is_approved %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br/>

  <h2>Applications (Pending)</h2>
  <table id="coursesTable" class="table mt-3">
    <thead>
    <tr id="headerRow">
      <th class="text-center">Course Number</th>
      <th class="text-center">Term</th>
      <th class="text-center">Name</th>
      <th class="text-center">Subject</th>
      <th class="text-center">User</th>
      <th class="text-center">Approved</th>
    </tr>
    </thead>

    <tbody>
    <% @applications.where(approved: false).each do |application| %>
      <tr>
        <td class="text-center"><%= application.course.course_number %></td>
        <td class="text-center"><%= application.course.term %></td>
        <td class="text-center"><%= application.course.name %></td>
        <td class="text-center"><%= application.course.subject %></td>
        <td class="text-center"><%= application.user.email %></td>
        <td class="text-center"><%= application.approved %></td>
        <td class="text-center">
          <div class="container">
            <div class="row">
              <div class="column">
                <div class="col">
                  <%= link_to "Show this Application", application, class: "btn btn-primary btn-block" %>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br/>

  <h2>Applications (Approved)</h2>
  <table id="coursesTable" class="table mt-3">
    <thead>
    <tr id="headerRow">
      <th class="text-center">Course Number</th>
      <th class="text-center">Term</th>
      <th class="text-center">Name</th>
      <th class="text-center">Subject</th>
      <th class="text-center">User</th>
      <th class="text-center">Approved</th>
      <th class="text-center">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @applications.where(approved: true).each do |application| %>
      <tr>
        <td class="text-center"><%= application.course.course_number %></td>
        <td class="text-center"><%= application.course.term %></td>
        <td class="text-center"><%= application.course.name %></td>
        <td class="text-center"><%= application.course.subject %></td>
        <td class="text-center"><%= application.user.email %></td>
        <td class="text-center"><%= application.approved %></td>
        <td class="text-center">
          <div class="container">
            <div class="row">
              <div class="column">
                <div class="col">
                  <%= link_to "Show this Application", application, class: "btn btn-primary btn-block" %>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark text-white">
  <div class="container text-center">
    <p>&copy; <%= Time.now.year %> Course: CSE 3901 | Section: 6442. All rights reserved.</p>
    <p>Instructor: Scott Sharkey</p>
    <p>Team Member: Jackie Boadi | Jiaming Cheng | Noah Hein | Roy Ji | Long Lin | Matthew Modica | Xianzhe Wang</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <% if user_signed_in? %>
      <a class="navbar-brand hover-underline" href="<%= root_path %>">Welcome, <%= current_user.email %>!</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Applications', applications_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Course History', enrollments_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Availability', availabilities_path, class: 'nav-link' %>
          </li>
          <% if current_user.role == "Admin" && current_user.is_approved == true %>
            <li class="nav-item">
              <%= link_to 'Recommendations', recommendations_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Admin Portal', admin_index_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Users', users_path, method: :get, class: "nav-link" %>
            </li>
<!--            <li class="nav-item">-->
              <%#= link_to 'Reload Courses', 'courses/reload', method: :get, class: "nav-link" %>
<!--            </li>-->
          <% end %>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, :method => :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Student Grader Manager</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>